# Generated by Django 3.1.3 on 2020-11-27 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='dislike_count',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='like_count',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
