# Generated by Django 3.1.3 on 2020-11-28 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_auto_20201127_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='dislike_count',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='post',
            name='like_count',
            field=models.CharField(max_length=12),
        ),
    ]
